"""Replace renderProducts with sorted layout - final clean fix"""
with open("goodlife-replica/admin.html", "rb") as f:
    d = bytearray(f.read())

ss = d.find(b"function renderProducts")
se = d.find(b"function showEditProduct", ss)

# Build using bytes concatenation - manually construct each line
lines = []

def L(s):
    lines.append(s.encode("utf-8"))

L('function renderProducts() {')
L('')
L('  var el = document.getElementById(\'productList\');')
L('')
L('  if (allProducts.length === 0) {')
L('    el.innerHTML = \'<div style="padding:60px;text-align:center;color:#999">No products found. Click "+ Add Product" to get started.</div>\';')
L('    document.getElementById(\'inventorySummary\').style.display = \'none\';')
L('    return;')
L('  }')
L('')
L('  // Sort alphabetically by name')
L('  var sorted = allProducts.slice().sort(function(a, b) {')
L('    var na = (a.name || \'\').toLowerCase();')
L('    var nb = (b.name || \'\').toLowerCase();')
L('    if (na < nb) return -1;')
L('    if (na > nb) return 1;')
L('    return 0;')
L('  });')
L('')
L('  var html = \'\';')
L('  var totalStock = 0;')
L('  var lowStock = 0;')
L('  var lowStockItems = [];')
L('  var categories = {};')
L('')
L('  for (var i = 0; i < sorted.length; i++) {')
L('')
L('    var p = sorted[i];')
L('    totalStock += (p.stock || 0);')
L('    if (p.stock !== undefined && p.stock < 20) { lowStock++; lowStockItems.push(p.name + \' (\' + p.stock + \')\'); }')
L('    if (!categories[p.category]) categories[p.category] = 0;')
L('    categories[p.category]++;')
L('    var stockClass = p.stock <= 0 ? \'stock-out\' : p.stock < 20 ? \'stock-low\' : \'stock-ok\';')
L('    var stockLabel = p.stock <= 0 ? \'Out of stock\' : p.stock + \' in stock\';')
L('')
L('    html += \'<div class="product-card">\' +')
L('      \'<div style="display:flex;gap:10px;flex:1;min-width:0">\' +')
L('')
L('      + (p.image ? \'<div style="width:44px;height:44px;flex-shrink:0;border-radius:6px;overflow:hidden;background:#f0f0f0"><img src="\' + p.image + \'" alt="\' + p.name + \'" style="width:100%;height:100%;object-fit:cover" onerror="this.remove()"></div>\' : \'\') +')
L('')
L('      \'<div style="min-width:0;flex:1">\' +')
L('      \'<div class="prod-name">\' + p.name + \'</div>\' +')
L('      \'<div class="prod-cat">\' + (p.category || \'\') + \' \' + (p.id || \'\') + \'</div>\' +')
L('      \'<div style="font-size:11px;color:#555;margin-top:2px">\' + (p.description ? p.description.substring(0,60) + (p.description.length > 60 ? \'...\' : \'\') : \'\') + \'</div>\' +')
L('    \'</div>\' +')
L('')
L('    \'<div style="display:flex;align-items:center;gap:8px">\' +')
L('')
L('      \'<div style="text-align:right;min-width:80px">\' +')
L('        \'<div class="prod-price">KSh \' + Number(p.price).toLocaleString() + \'</div>\' +')
L('        \'<div class="prod-stock \' + stockClass + \'">\' + stockLabel + \'</div>\' +')
L('      \'</div>\' +')
L('')
L('      \'<div style="display:grid;grid-template-columns:1fr 1fr;gap:2px;width:80px">\' +')
L('        \'<button onclick="quickStock(\\\'\' + p.id + \'\\\',-1)" title="Remove 1" style="padding:2px 6px;font-size:11px;background:#ffebee;color:#c62828;border:1px solid #ef9a9a;border-radius:3px;cursor:pointer">-1</button>\' +')
L('        \'<button onclick="quickStock(\\\'\' + p.id + \'\\\',-5)" title="Remove 5" style="padding:2px 6px;font-size:11px;background:#ffebee;color:#c62828;border:1px solid #ef9a9a;border-radius:3px;cursor:pointer">-5</button>\' +')
L('        \'<button onclick="quickStock(\\\'\' + p.id + \'\\\',1)" title="Add 1" style="padding:2px 6px;font-size:11px;background:#e8f5e9;color:#2e7d32;border:1px solid #a5d6a7;border-radius:3px;cursor:pointer">+1</button>\' +')
L('        \'<button onclick="quickStock(\\\'\' + p.id + \'\\\',5)" title="Add 5" style="padding:2px 6px;font-size:11px;background:#e8f5e9;color:#2e7d32;border:1px solid #a5d6a7;border-radius:3px;cursor:pointer">+5</button>\' +')
L('      \'</div>\' +')
L('')
L('    \'</div>\' +')
L('')
L('    \'<div style="display:flex;gap:4px">\' +')
L('')
L('      \'<button class="btn btn-primary" onclick="showEditProduct(\\\'\' + p.id + \'\\\')" style="font-size:11px;padding:6px 12px">Edit</button>\' +')
L('')
L('      + (p.featured ? \'<button onclick="toggleFeatured(\\\'\' + p.id + \'\\\',false)" style="font-size:11px;padding:6px 10px;background:#e8f5e9;color:#2e7d32;border:1px solid #2e7d32;border-radius:4px;cursor:pointer" title="Click to unfeature">\\u2b50 Featured</button>\' : \'<button onclick="toggleFeatured(\\\'\' + p.id + \'\\\',true)" style="font-size:11px;padding:6px 10px;background:#f5f5f5;color:#888;border:1px solid #ddd;border-radius:4px;cursor:pointer">\\u2b50 Feature</button>\') +')
L('')
L('      + (p.specialOffer ? \'<button onclick="toggleSpecial(\\\'\' + p.id + \'\\\',false)" style="font-size:11px;padding:6px 10px;background:#fff3e0;color:#e65100;border:1px solid #e65100;border-radius:4px;cursor:pointer" title="Click to remove sale">\\ud83d\\udd25 On Sale</button>\' : \'<button onclick="toggleSpecial(\\\'\' + p.id + \'\\\',true)" style="font-size:11px;padding:6px 10px;background:#f5f5f5;color:#888;border:1px solid #ddd;border-radius:4px;cursor:pointer">\\ud83d\\udd25 Offer</button>\') +')
L('')
L('      \'<button class="btn" onclick="deleteProduct(\\\'\' + p.id + \'\\\',\\\'\' + p.name.replace(/\'/g,\\\'\\\\\\\'\') + \'\\\')" style="font-size:11px;padding:6px 12px;background:#ffebee;color:#c62828;border:none;border-radius:4px;cursor:pointer">Del</button>\' +')
L('')
L('    \'</div></div>\';')
L('')
L('  }')
L('')
L('  el.innerHTML = html;')
L('')
L('  // Inventory summary')
L('  var catCount = Object.keys(categories).length;')
L('  document.getElementById(\'inventorySummary\').style.display = \'block\';')
L('  document.getElementById(\'inventorySummary\').innerHTML =')
L('    \'<strong>\\ud83d\\udcca Inventory Summary</strong> \\u2014 \' + sorted.length + \' products across \' + catCount + \' categories &nbsp;|&nbsp; \' +')
L('    \'<span class="stock-ok">\\u2705 \' + (sorted.length - lowStock) + \' in stock</span> &nbsp;|&nbsp; \' +')
L('    \'<span class="stock-low">\\u26a0\\ufe0f \' + lowStock + \' low stock</span> &nbsp;|&nbsp; \' +')
L('    \'\\ud83d\\udce6 \' + totalStock + \' total units\' +')
L('    (lowStockItems.length > 0 ? \'<div style="margin-top:10px;font-size:12px;line-height:1.6">\' +')
L('      \'<strong style="color:#c62828">\\u26a0\\ufe0f Low Stock Items:</strong> \' +')
L('      lowStockItems.join(\' &nbsp;|&nbsp; \') +')
L('    \'</div>\' : \'\');')
L('')
L('}')

new_bytes = b"\r\n".join(lines)

d[ss:se] = new_bytes

with open("goodlife-replica/admin.html", "wb") as f:
    f.write(d)

print(f"Replaced renderProducts: {len(new_bytes)} bytes")

# Validate JS
script_start = d.find(b"<script>") + len(b"<script>")
script_end = d.find(b"</script>", script_start)
js = d[script_start:script_end]
import tempfile, subprocess, os
with tempfile.NamedTemporaryFile(suffix=".js", delete=False) as f:
    f.write(js)
    fn = f.name
r = subprocess.run(["node", "--check", fn], capture_output=True, text=True, timeout=10, encoding='utf-8')
os.unlink(fn)
if r.returncode == 0:
    print("JS syntax: OK")
else:
    print("JS syntax ERROR:", r.stderr[:1500])
